type WeeklyShareStats = {
  score: number;
  daysLogged: number;
  daysTotal: number;
  totalBlocks: number;
  deepMinutes?: number;
  goalMinutesPerDay?: number;
  goalKeyword?: string;
};

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
  const radius = Math.min(r, w / 2, h / 2);
  ctx.beginPath();
  ctx.moveTo(x + radius, y);
  ctx.arcTo(x + w, y, x + w, y + h, radius);
  ctx.arcTo(x + w, y + h, x, y + h, radius);
  ctx.arcTo(x, y + h, x, y, radius);
  ctx.arcTo(x, y, x + w, y, radius);
  ctx.closePath();
}

export async function downloadWeeklyShareCard(stats: WeeklyShareStats) {
  const w = 1200;
  const h = 630;
  const canvas = document.createElement("canvas");
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas not supported");

  // Background
  const g = ctx.createLinearGradient(0, 0, w, h);
  g.addColorStop(0, "#f7f2e8");
  g.addColorStop(1, "#eef7f5");
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, w, h);

  // Soft grid
  ctx.globalAlpha = 0.08;
  ctx.strokeStyle = "#111827";
  for (let x = 0; x < w; x += 48) {
    ctx.beginPath();
    ctx.moveTo(x, 0);
    ctx.lineTo(x, h);
    ctx.stroke();
  }
  for (let y = 0; y < h; y += 48) {
    ctx.beginPath();
    ctx.moveTo(0, y);
    ctx.lineTo(w, y);
    ctx.stroke();
  }
  ctx.globalAlpha = 1;

  // Header
  ctx.fillStyle = "#0f172a";
  ctx.font = "700 48px system-ui, -apple-system, Segoe UI, sans-serif";
  ctx.fillText("RutineIQ", 70, 110);
  ctx.font = "500 22px system-ui, -apple-system, Segoe UI, sans-serif";
  ctx.fillStyle = "rgba(15,23,42,0.70)";
  ctx.fillText("Weekly Snapshot", 70, 145);

  // Score pill
  const pillX = 70;
  const pillY = 185;
  const pillW = 520;
  const pillH = 140;
  ctx.fillStyle = "rgba(255,255,255,0.75)";
  ctx.strokeStyle = "rgba(15,23,42,0.10)";
  ctx.lineWidth = 2;
  roundRect(ctx, pillX, pillY, pillW, pillH, 24);
  ctx.fill();
  ctx.stroke();

  ctx.fillStyle = "#0f172a";
  ctx.font = "700 72px system-ui, -apple-system, Segoe UI, sans-serif";
  ctx.fillText(String(Math.max(0, Math.min(100, Math.round(stats.score)))), pillX + 36, pillY + 96);
  ctx.font = "600 24px system-ui, -apple-system, Segoe UI, sans-serif";
  ctx.fillStyle = "rgba(15,23,42,0.75)";
  ctx.fillText("Consistency Score", pillX + 170, pillY + 78);
  ctx.font = "500 18px system-ui, -apple-system, Segoe UI, sans-serif";
  ctx.fillStyle = "rgba(15,23,42,0.60)";
  ctx.fillText(`${stats.daysLogged}/${stats.daysTotal} days logged`, pillX + 170, pillY + 108);

  // Stats cards
  const cards = [
    { label: "Total blocks", value: String(stats.totalBlocks) },
    { label: "Deep work (min)", value: stats.deepMinutes != null ? String(stats.deepMinutes) : "-" },
    { label: "Goal (min/day)", value: stats.goalMinutesPerDay != null ? String(stats.goalMinutesPerDay) : "-" }
  ];

  const cardW = 330;
  const cardH = 120;
  const startX = 70;
  const startY = 360;
  const gap = 22;

  for (let i = 0; i < cards.length; i++) {
    const c = cards[i]!;
    const x = startX + i * (cardW + gap);
    const y = startY;
    ctx.fillStyle = "rgba(255,255,255,0.70)";
    ctx.strokeStyle = "rgba(15,23,42,0.10)";
    ctx.lineWidth = 2;
    roundRect(ctx, x, y, cardW, cardH, 22);
    ctx.fill();
    ctx.stroke();

    ctx.fillStyle = "rgba(15,23,42,0.60)";
    ctx.font = "600 18px system-ui, -apple-system, Segoe UI, sans-serif";
    ctx.fillText(c.label, x + 24, y + 44);
    ctx.fillStyle = "#0f172a";
    ctx.font = "700 44px system-ui, -apple-system, Segoe UI, sans-serif";
    ctx.fillText(c.value, x + 24, y + 92);
  }

  // Footer
  ctx.fillStyle = "rgba(15,23,42,0.55)";
  ctx.font = "500 16px system-ui, -apple-system, Segoe UI, sans-serif";
  ctx.fillText("Generated by RutineIQ", 70, 585);
  if (stats.goalKeyword) {
    ctx.fillText(`Goal keyword: "${stats.goalKeyword}"`, 70, 610);
  }

  const blob: Blob = await new Promise((resolve, reject) => {
    canvas.toBlob((b) => {
      if (!b) reject(new Error("Failed to render image"));
      else resolve(b);
    }, "image/png");
  });

  downloadBlob(blob, "routineiq-weekly-snapshot.png");
}

